### PR TITLE
 fix(docs): resolve MDX parsing error in installation tabs

### PR DESCRIPTION
**Pull request by dushyant-hada-90**
## Description
This PR fixes a critical MDX compilation error (Expected a closing tag for <Tab>) that causes a 500 server error on the Installation documentation page.

## Root Cause:
The bug was inadvertently introduced in commit 598205165. The bash commands inside the "from source" <Tab> component were placed on a single line. This formatting caused the underlying Markdown parser to misinterpret the closing backticks (```), which subsequently swallowed the closing JSX </Tab> tag and broke the page build. Additionally, the bash commands were chained with spaces instead of newlines or && operators, causing terminal execution failures.

## Changes Made:

Reformatted the MDX code blocks across all tabs so that the opening and closing code fences (```) are placed on their own distinct lines, satisfying the strict MDX parser requirements.

Separated the chained bash commands (cd, pnpm install, pnpm build, etc.) in the "from source" tab onto individual lines to ensure they execute sequentially and correctly in the user's terminal.

## Testing:

Verified locally that the docs page now compiles successfully without the Fast Refresh/Webpack serialization errors.

### CODE REVIEW

**Comment by i-trytoohard** [comment]
## Triage Notes — Confirmed ✅

**Bug verified on `main`.** The `installation.mdx` file has malformed single-line code fences inside the `<Tab>` components — the opening fence, bash commands, and closing fence are all on the same line. MDX's parser swallows the trailing backticks and fails to register the closing `</Tab>` → `Expected a closing tag for <Tab>` → **500 on the installation docs page**.

**Root cause** matches the description — introduced when the fences were collapsed to single lines. The `from source` tab triggered the actual 500, but all four tabs had the same anti-pattern, so fixing all of them is the right call.

**Fix is correct and surgical:**
- ✅ Multi-line fenced code blocks — the idiomatic MDX approach
- ✅ 1 file, +22/−5, no scope creep
- ✅ Mergeable, no conflicts

Reviewed by AO (automated triage). Ready for maintainer approval/merge.

**Comment by i-trytoohard** [comment]
## Update — Website is being redone 🚧

Heads up @dushyant-hada-90 — thanks for the triage and the fix! However, the **website is currently being fully redone**, so PRs to the existing website (including this docs page) **won't be accepted** at this time.

Once the website redo is complete, you'll be able to contribute directly to the new site. In the meantime, if you'd like to help with the website effort, please **contact shiawase22 on discord to know how you can contribute to the rewrite** — she'll guide you on how to get involved.

Appreciate the contribution! 🙏
